CREATE TABLE `device_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`rfPath` varchar(64),
	`rxCenterFreq` int NOT NULL,
	`txCenterFreq` int NOT NULL,
	`rxBandwidth` int NOT NULL,
	`txBandwidth` int NOT NULL,
	`rxLnaGain` int NOT NULL,
	`rxPgaGain` int NOT NULL,
	`rxVgaGain` int NOT NULL,
	`txGain` int NOT NULL,
	`clockSource` enum('internal','devboard','external') NOT NULL,
	`externalClockFreq` int,
	`dacTuning` int,
	`sampleRate` int NOT NULL,
	`dataFormat` varchar(32) NOT NULL,
	`blockSize` int NOT NULL,
	`connectionType` enum('usb','pcie') NOT NULL,
	`lnaOn` boolean NOT NULL DEFAULT false,
	`paOn` boolean NOT NULL DEFAULT false,
	`gpsdoOn` boolean NOT NULL DEFAULT false,
	`oscOn` boolean NOT NULL DEFAULT false,
	`mode` enum('rx','tx','trx') NOT NULL DEFAULT 'rx',
	`isDefault` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `device_configs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `device_status_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`configId` int,
	`connectionState` enum('connected','disconnected','streaming','error') NOT NULL,
	`deviceId` varchar(128),
	`throughputMbps` int,
	`droppedSamples` int,
	`errorCount` int,
	`notes` text,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `device_status_log_id` PRIMARY KEY(`id`)
);
